INSERT INTO `CLIENTE` VALUES (1, 'Agatha');
INSERT INTO `CLIENTE` VALUES (2, 'Danilo');
INSERT INTO `CLIENTE` VALUES (3, 'Luana');
INSERT INTO `CLIENTE` VALUES (4, 'Adrielly');
INSERT INTO `CLIENTE` VALUES (5, 'Belinha');

